In [9]:
import numpy as np
import pandas as pd
import ast
import pickle
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

movies = pd.read_csv(
    r'C:\Users\Lenovo\PycharmProjects\Movie_Recommender_system_with_Sentiment_analysis\data\tmdb_5000_movies.csv'
)

credits = pd.read_csv(
    r'C:\Users\Lenovo\PycharmProjects\Movie_Recommender_system_with_Sentiment_analysis\data\tmdb_5000_credits.csv'
)

mymovies = pd.read_csv(
    r'C:\Users\Lenovo\PycharmProjects\Movie_Recommender_system_with_Sentiment_analysis\data\mymoviedb.csv',
    engine='python',
    encoding='latin1',
    on_bad_lines='skip'
)

imdb = pd.read_csv(
    r'C:\Users\Lenovo\PycharmProjects\Movie_Recommender_system_with_Sentiment_analysis\data\movies_metadata.csv',
    engine='python',
    encoding='latin1',
    on_bad_lines='skip'
)

In [10]:

movies = movies.merge(credits, on='title')

In [12]:
print(mymovies.columns)

Index(['Release_Date', 'Title', 'Overview', 'Popularity', 'Vote_Count',
       'Vote_Average', 'Original_Language', 'Genre', 'Poster_Url'],
      dtype='object')

In [13]:

movies['title_key'] = movies['title'].str.lower().str.strip()
mymovies['title_key'] = mymovies['Title'].str.lower().str.strip()

In [14]:

movies = movies.merge(
    mymovies[['title_key','Poster_Url']],
    on='title_key',
    how='left'
)

In [15]:

movies['title_key'] = movies['title'].str.lower().str.strip()
imdb['title_key'] = imdb['title'].str.lower().str.strip()

In [16]:

movies = movies.merge(
    imdb[['title_key','imdb_id']],
    on='title_key',
    how='left'
)

In [17]:


movies.drop(columns=['title_key'], inplace=True)

In [18]:


movies = movies[['movie_id','title','overview','genres','keywords','cast','crew','Poster_Url','vote_average','imdb_id']]

movies.dropna(inplace=True)

In [19]:

def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name'])
    return L

movies['genres'] = movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)

In [20]:

def convert_cast(text):
    L = []
    counter = 0

    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
            counter += 1
        else:
            break

    return L

movies['cast'] = movies['cast'].apply(convert_cast)

In [21]:

def fetch_director(text):

    L = []

    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])

    return L

In [22]:

movies['crew'] = movies['crew'].apply(fetch_director)



def collapse(L):

    L1 = []

    for i in L:
        L1.append(i.replace(" ",""))

    return L1

In [23]:

movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [24]:

movies['original_overview'] = movies['overview']
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [69]:

movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

# Keep required columns
new = movies[['movie_id','title','tags','original_overview','Poster_Url','overview','cast','crew','vote_average','imdb_id']]

# Convert list → string
new['tags'] = new['tags'].apply(lambda x:" ".join(x))

# Lowercase tags only
new['tags'] = new['tags'].apply(lambda x:x.lower())

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_17896\3375860967.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['tags'] = new['tags'].apply(lambda x:" ".join(x))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_17896\3375860967.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['tags'] = new['tags'].apply(lambda x:x.lower())

In [70]:
new.head()

,movie_id,title,tags,original_overview,Poster_Url,overview,cast,crew,vote_average,imdb_id
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di...","In the 22nd century, a paraplegic Marine is di...",https://image.tmdb.org/t/p/original/jRXYjXNq0C...,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],7.2,tt0499549
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha...","Captain Barbossa, long believed to be dead, ha...",https://image.tmdb.org/t/p/original/2YMnBRh8F6...,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],6.9,tt0449088
2,206647,Spectre,a cryptic message from bond’s past sends him o...,A cryptic message from Bond’s past sends him o...,https://image.tmdb.org/t/p/original/zj8ongFhtW...,"[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],6.3,tt2379713
3,49026,The Dark Knight Rises,following the death of district attorney harve...,Following the death of District Attorney Harve...,https://image.tmdb.org/t/p/original/85cWkCVfti...,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],7.6,tt1345836
4,49529,John Carter,"john carter is a war-weary, former military ca...","John Carter is a war-weary, former military ca...",https://image.tmdb.org/t/p/original/7GSSyUUgUE...,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],6.1,tt0401729

In [71]:
new['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [72]:

cv = CountVectorizer(max_features=5000, stop_words='english')

vectors = cv.fit_transform(new['tags']).toarray()

In [73]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\lenovo\pycharmprojects\movie_recommender_system_with_sentiment_analysis\.venv\lib\site-packages (3.9.3)
Requirement already satisfied: click in c:\users\lenovo\pycharmprojects\movie_recommender_system_with_sentiment_analysis\.venv\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\lenovo\pycharmprojects\movie_recommender_system_with_sentiment_analysis\.venv\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\lenovo\pycharmprojects\movie_recommender_system_with_sentiment_analysis\.venv\lib\site-packages (from nltk) (2026.2.28)
Requirement already satisfied: tqdm in c:\users\lenovo\pycharmprojects\movie_recommender_system_with_sentiment_analysis\.venv\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in c:\users\lenovo\pycharmprojects\movie_recommender_system_with_sentiment_analysis\.venv\lib\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 25.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [74]:
import nltk
from nltk.stem.porter import PorterStemmer

In [75]:
ps= PorterStemmer()
def stem(text):
    y =[]
    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [76]:
new['tags'] = new['tags'].apply(stem)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_17896\2183557711.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['tags'] = new['tags'].apply(stem)

In [77]:

similarity = cosine_similarity(vectors)

In [78]:
similarity[0]

array([1.        , 0.08920516, 0.05751973, ..., 0.05661385, 0.05847053,
       0.02531848], shape=(3914,))

In [79]:
def recommend(movie):
    movie_index = new[new['title'] == movie].index[0]
    distance = similarity[movie_index]
    movies_list = sorted(list(enumerate(distance)), key=lambda x: x[1], reverse=True)[1:6]
    for i in movies_list:
        print(i[0])

In [80]:
new[new['title'] == 'Avatar']

,movie_id,title,tags,original_overview,Poster_Url,overview,cast,crew,vote_average,imdb_id
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa...","In the 22nd century, a paraplegic Marine is di...",https://image.tmdb.org/t/p/original/jRXYjXNq0C...,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],7.2,tt0499549

In [81]:
recommend('Avatar')

788
2725
827
1829
1566

In [82]:
import pickle

pickle.dump(new.to_dict(), open('../movies.pkl', 'wb'))
pickle.dump(similarity, open('../similarity.pkl', 'wb'))

print("Model files saved successfully!")

Model files saved successfully!